### ISSUE TITLE
Temp media branch doesn't merge after saving a menu

### ISSUE THREAD

**Issue by CalebBarnes** [TylerBarnes/wordsby#47]
Automatically merge branches after saving a menu

**Comment by TylerBarnes** [comment]
This is fixed via https://github.com/TylerBarnes/wordsby-admin/commit/432598ab51c6fa2536390fa60c0b3772835a55bf and https://github.com/TylerBarnes/wordsby-admin/commit/49baf8d499463687e699b06ac7a2212ea67217fa
