### ISSUE TITLE
post_date ignores date and time formatting settings

### ISSUE THREAD

**Issue by CalebBarnes** [TylerBarnes/wordsby#51]
In Wordpress settings -> general there are post date and time formatting options but they are ignored by Wordsby.

**Comment by TylerBarnes** [comment]
Thanks!
In which places are they ignored?

**Comment by CalebBarnes** [comment]
I just tested it in a custom post type "news". 

`export const NewsPostQuery = graphql`
  query NewsSinglePost($id: Int!) {
    wordsbyCollections(ID: { eq: $id }) {
      post_title
      post_content
      post_date
      featured_img {
        childImageSharp {
          fluid(quality: 80, maxWidth: 1440) {
            ...GatsbyImageSharpFluid
          }
        }
      }
    }
  }
`;
`

In this query **post_date** === **2019-03-13 21:44:37**

**Comment by TylerBarnes** [comment]
Thanks for that. I guess it doesn't matter too much but what format did you set in settings?

**Comment by CalebBarnes** [comment]
With my current settings it should look like 03/13/2019 5:00pm

**Comment by CalebBarnes** [comment]
It might also be good to separate it into post_date and post_time.
