### ISSUE TITLE
Using an archive page as the home page fails to set the page path

### ISSUE THREAD

**Issue by CalebBarnes** [TylerBarnes/wordsby#58]
**The plugin "gatsby-plugin-wordsby" must set the page path when creating a page**

```{ path: '',
  component:
   '/Users/caleb/Documents/GitHub/wordsby-fresh/src/templates/archive/post.js',
  context:
   { latestBuild: 1558126161,
     wpUrl: 'https://bare-starter.barework.com',
     archive: true,
     id: 23,
     post_type: 'post',
     pageNumber: 0,
     humanPageNumber: 1,
     skip: 0,
     limit: 20,
     numberOfPages: 1,
     previousPagePath: '',
     nextPagePath: '' }    ###}
error See the documentation for createPage https://www.gatsbyjs.org/docs/actions/#createPage```

**Comment by TylerBarnes** [comment]
Can you provide some more context?

**Comment by CalebBarnes** [comment]
I have an archive page named 'posts' and if I set that as the home page in WordPress I get that error. It's failing to create the page.

**Comment by TylerBarnes** [comment]
If it's not the home page or if it's not an archive page does it build?

**Comment by CalebBarnes** [comment]
Yes, it only builds if it's not an archive page or if it's not the home page.

**Comment by TylerBarnes** [comment]
Ok, probably it's because the path in wordsby is `/` and somewhere that's not accounted for for archive pages

**Comment by TylerBarnes** [comment]
Until this is fixed do you need a paginated home page? If not I would just list x number of posts on your  homepage and then have a separate archive page and have the next page button link to `/posts/page/2` (or whatever your archive page 2 url is).
